config/routes.rb
VideoDepot::Application.routes.draw do
  get "admin" => "admin#index"

  controller :sessions do
    get     "login"   => :new
    post    "login"   => :create
    delete  "logout"  => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :orders

  resources :ratings

  resources :movie_categories

  resources :categories

  resources :cart_items

  resources :carts

  get "store/index"

  resources :movies do
    get :who_rent, :on => :member
  end

  match 'rent-history' => 'orders#index'

  root :to => "store#index", :as => 'store'

end

app/models/rating.rb
class Rating < ActiveRecord::Base

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.xml
  def create
    @rating = Rating.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to(@rating, :notice => 'Rating was successfully created.') }
        format.xml  { render :xml => @rating, :status => :created, :location => @rating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to(@rating, :notice => 'Rating was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to(ratings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.code %></td>
    <td><%= rating.title %></td>
    <td><%= rating.description %></td>
    <td><%= rating.image %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @rating.code %>
</p>

<p>
  <b>Title:</b>
  <%= @rating.title %>
</p>

<p>
  <b>Description:</b>
  <%= @rating.description %>
</p>

<p>
  <b>Image:</b>
  <%= @rating.image %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>