config/routes.rb
VideoDepot::Application.routes.draw do
  get "admin" => "admin#index"

  controller :sessions do
    get     "login"   => :new
    post    "login"   => :create
    delete  "logout"  => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :orders

  resources :ratings

  resources :movie_categories

  resources :categories

  resources :cart_items

  resources :carts

  get "store/index"

  resources :movies do
    get :who_rent, :on => :member
  end

  match 'rent-history' => 'orders#index'

  root :to => "store#index", :as => 'store'

end

app/models/movie_category.rb
class MovieCategory < ActiveRecord::Base
	belongs_to :movie
	belongs_to :category
end

app/controllers/movie_categories_controller.rb
class MovieCategoriesController < ApplicationController
  # GET /movie_categories
  # GET /movie_categories.xml
  def index
    @movie_categories = MovieCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @movie_categories }
    end
  end

  # GET /movie_categories/1
  # GET /movie_categories/1.xml
  def show
    @movie_category = MovieCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @movie_category }
    end
  end

  # GET /movie_categories/new
  # GET /movie_categories/new.xml
  def new
    @movie_category = MovieCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @movie_category }
    end
  end

  # GET /movie_categories/1/edit
  def edit
    @movie_category = MovieCategory.find(params[:id])
  end

  # POST /movie_categories
  # POST /movie_categories.xml
  def create
    @movie_category = MovieCategory.new(params[:movie_category])

    respond_to do |format|
      if @movie_category.save
        format.html { redirect_to(@movie_category, :notice => 'Movie category was successfully created.') }
        format.xml  { render :xml => @movie_category, :status => :created, :location => @movie_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @movie_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /movie_categories/1
  # PUT /movie_categories/1.xml
  def update
    @movie_category = MovieCategory.find(params[:id])

    respond_to do |format|
      if @movie_category.update_attributes(params[:movie_category])
        format.html { redirect_to(@movie_category, :notice => 'Movie category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @movie_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_categories/1
  # DELETE /movie_categories/1.xml
  def destroy
    @movie_category = MovieCategory.find(params[:id])
    @movie_category.destroy

    respond_to do |format|
      format.html { redirect_to(movie_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/movie_categories_helper.rb
module MovieCategoriesHelper
end

app/views/movie_categories/_form.html.erb
<%= form_for(@movie_category) do |f| %>
  <% if @movie_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_category.errors.count, "error") %> prohibited this movie_category from being saved:</h2>

      <ul>
      <% @movie_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br />
    <%= f.text_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_categories/edit.html.erb
<h1>Editing movie_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_category %> |
<%= link_to 'Back', movie_categories_path %>

app/views/movie_categories/index.html.erb
<h1>Listing movie_categories</h1>

<table>
  <tr>
    <th>Movie</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movie_categories.each do |movie_category| %>
  <tr>
    <td><%= movie_category.movie_id %></td>
    <td><%= movie_category.category_id %></td>
    <td><%= link_to 'Show', movie_category %></td>
    <td><%= link_to 'Edit', edit_movie_category_path(movie_category) %></td>
    <td><%= link_to 'Destroy', movie_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie category', new_movie_category_path %>

app/views/movie_categories/new.html.erb
<h1>New movie_category</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_categories_path %>

app/views/movie_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Movie:</b>
  <%= @movie_category.movie_id %>
</p>

<p>
  <b>Category:</b>
  <%= @movie_category.category_id %>
</p>


<%= link_to 'Edit', edit_movie_category_path(@movie_category) %> |
<%= link_to 'Back', movie_categories_path %>